### ISSUE TITLE
程序错误

### ISSUE THREAD

**Issue by lifeng9797** [huangdibujitaijianji/LCM-Captioner#1]
## ❓ Questions and Help
2023-08-18T01:50:59 ERROR: 'M4CCaptioner' object has no attribute 'module'
Traceback (most recent call last):
  File "run.py", line 105, in <module>
    run()
  File "run.py", line 94, in run
    trainer.train()
  File "/public/home/lifeng/project/LCM-Captioner-master/pythia/trainers/base_trainer.py", line 240, in train
    should_break = self._logistics(report)
  File "/public/home/lifeng/project/LCM-Captioner-master/pythia/trainers/base_trainer.py", line 349, in _logistics
    should_break = self._try_full_validation()
  File "/public/home/lifeng/project/LCM-Captioner-master/pythia/trainers/base_trainer.py", line 364, in _try_full_validation
    stop = self.early_stopping(self.current_iteration, meter)
  File "/public/home/lifeng/project/LCM-Captioner-master/pythia/utils/early_stopping.py", line 69, in __call__
    self.checkpoint.save(iteration, update_best=True)
  File "/public/home/lifeng/project/LCM-Captioner-master/pythia/utils/checkpoint.py", line 224, in save
    model = model.module
  File "/public/home/lifeng/anaconda3/envs/lcm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 778, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'M4CCaptioner' object has no attribute 'module'

请问你的运行没有这个问题吗？是怎么解决的？

**Comment by DengHY258** [comment]
你好。我们运行时并没有出现类似的问题。这部分程序来自https://github.com/facebookresearch/mmf/tree/project/m4c/projects/M4C_Captioner，
你可以在此寻求进一步的信息。checkpoint.py的224行附近的功能是将模型权重进行保存，我认为修改的重点是将实际的模型部分赋值给model变量，使得后面ckpt字典里的“model”保存到模型参数，就能够运行成功。你初步可以尝试将224行注释掉，看看问题有没有解决。
